# Generated by Django 5.0.3 on 2024-04-01 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('a', 'Pass'), ('b', 'Credit'), ('c', 'Distinction'), ('d', 'High Distinction')], max_length=1)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ontrack.units')),
            ],
        ),
    ]
