# Generated by Django 5.0.3 on 2024-04-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
