# Generated by Django 5.0.3 on 2024-04-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontrack', '0002_rename_units_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='level',
        ),
    ]
