# Generated by Django 5.0.3 on 2024-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontrack', '0003_remove_submission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='level',
            field=models.CharField(choices=[('a', 'Pass'), ('b', 'Credit'), ('c', 'Distinction'), ('d', 'High Distinction')], default='a', max_length=30),
            preserve_default=False,
        ),
    ]
